#!/bin/bash

echo AvalonStudio Plugin

mkdir -p $2AvalonStudio/bin/$3/$4/Plugins && cp $1 $2AvalonStudio/bin/$3/$4/Plugins/$5

if [ -z "$6" ]
  then
    mkdir -p $2AvalonStudioBuild/bin/$3/$4/Plugins && cp $1 $2AvalonStudioBuild/bin/$3/$4/Plugins/$5
fi
